name: gp_ng_examples
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.8.13
  - readline=8.1.2
  - setuptools=63.4.1
  - sqlite=3.39.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - asciitree==0.3.3
    - asttokens==2.0.8
    - atomicwrites==1.4.1
    - augment-nd==0.1.2
    - backcall==0.2.0
    - black==22.6.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - decorator==5.1.1
    - entrypoints==0.4
    - executing==1.0.0
    - fasteners==0.17.3
    - google-apitools==0.5.32
    - google-auth==2.11.0
    - gunpowder==1.2.2
    - h5py==3.7.0
    - httplib2==0.20.4
    - idna==3.3
    - imagecodecs==2022.8.8
    - imageio==2.21.2
    - ipython==8.4.0
    - jedi==0.18.1
    - matplotlib-inline==0.1.6
    - mypy-extensions==0.4.3
    - natsort==8.1.0
    - networkx==2.8.6
    - neuroglancer==2.29
    - numcodecs==0.10.2
    - numpy==1.23.2
    - oauth2client==4.1.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - parso==0.8.3
    - pathspec==0.10.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - platformdirs==2.5.2
    - prompt-toolkit==3.0.30
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pywavelets==1.3.0
    - requests==2.28.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.1
    - six==1.16.0
    - stack-data==0.5.0
    - tifffile==2022.8.12
    - tomli==2.0.1
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.3.0
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - zarr==2.12.0
